/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Summary = IDL.Record({
  'remaining' : IDL.Nat,
  'totalConsumed' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const Time = IDL.Int;
export const WaterEntry = IDL.Record({
  'id' : IDL.Nat64,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteEntry' : IDL.Func([IDL.Nat64], [], []),
  'getDailyGoal' : IDL.Func([], [IDL.Nat], ['query']),
  'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getTodaySummary' : IDL.Func([], [Summary], ['query']),
  'getTodaysEntries' : IDL.Func([], [IDL.Vec(WaterEntry)], ['query']),
  'getWeeklyEntries' : IDL.Func([], [IDL.Vec(WaterEntry)], ['query']),
  'logWaterIntake' : IDL.Func([IDL.Nat, IDL.Nat64], [], []),
  'setDailyGoal' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Summary = IDL.Record({
    'remaining' : IDL.Nat,
    'totalConsumed' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const Time = IDL.Int;
  const WaterEntry = IDL.Record({
    'id' : IDL.Nat64,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteEntry' : IDL.Func([IDL.Nat64], [], []),
    'getDailyGoal' : IDL.Func([], [IDL.Nat], ['query']),
    'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getTodaySummary' : IDL.Func([], [Summary], ['query']),
    'getTodaysEntries' : IDL.Func([], [IDL.Vec(WaterEntry)], ['query']),
    'getWeeklyEntries' : IDL.Func([], [IDL.Vec(WaterEntry)], ['query']),
    'logWaterIntake' : IDL.Func([IDL.Nat, IDL.Nat64], [], []),
    'setDailyGoal' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };