/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Summary {
  'remaining' : bigint,
  'totalConsumed' : bigint,
  'percentage' : bigint,
}
export type Time = bigint;
export interface WaterEntry {
  'id' : bigint,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface _SERVICE {
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getDailyGoal' : ActorMethod<[], bigint>,
  'getStreak' : ActorMethod<[], bigint>,
  'getTodaySummary' : ActorMethod<[], Summary>,
  'getTodaysEntries' : ActorMethod<[], Array<WaterEntry>>,
  'getWeeklyEntries' : ActorMethod<[], Array<WaterEntry>>,
  'logWaterIntake' : ActorMethod<[bigint, bigint], undefined>,
  'setDailyGoal' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];